{% set name = "k3d" %}
{% set version = "2.6.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|upper }}-{{ version }}.tar.gz
  sha256: 70528a459dd92fb6e4d32b67f187c0771f735a0c3460148ca061d208673485e5

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - setuptools
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ipywidgets >=7.0.1
    - ipydatawidgets
    - traittypes
    - traitlets
    - numpy >=1.11.0
test:
  commands:
    - cd {{ SRC_DIR }}/js && npm install && xvfb-run -a grunt test  # [linux]
  requires:
    - grunt
    - nodejs

about:
  home: http://github.com/K3D-tools/K3D-jupyter
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Jupyter notebook extension for 3D visualization.'
  dev_url: https://github.com/K3D-tools/K3D-jupyter

extra:
  recipe-maintainers:
    - renefritze
    - tgandor
    - artur-trzesiok
    - marcinofulus
