{% set name = "k3d" %}
{% set version = "2.14.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d8818158ea83cce35386e02f396bea60a6f6c2f2590e7dcfe491b60c1f6952f8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
    - jupyterlab ~=3.0
    - hatchling >=1.10.0
    - hatch-nodejs-version >=0.3.0
  run:
    - python >=3.7
    - ipywidgets >=7.0.1
    - traittypes
    - traitlets
    - numpy >=1.11.0
    - msgpack-python
test:
  imports:
    - k3d
  requires:
    - pip
    - jupyterlab ~=3.0
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - cat labextensions | grep "k3d.*OK"  # [unix]

about:
  home: http://github.com/K3D-tools/K3D-jupyter
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Jupyter notebook extension for 3D visualization.
  dev_url: https://github.com/K3D-tools/K3D-jupyter

extra:
  recipe-maintainers:
    - tgandor
    - artur-trzesiok
    - marcinofulus
