{% set name = "k3d" %}
{% set version = "2.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|upper }}-{{ version }}.tar.gz
  sha256: aee704cf3cc75cf55b31ae9c3197d7e802b26cf73f2d101385b4e18953804be1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - setuptools
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ipywidgets >=7.0.1
    - ipydatawidgets
    - traittypes
    - traitlets
    - numpy >=1.11.0
test:
  commands:
    - cd {{ SRC_DIR }}/js && npm install && xvfb-run -a grunt test  # [linux]
  requires:
    - grunt
    - nodejs

about:
  home: http://github.com/K3D-tools/K3D-jupyter
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Jupyter notebook extension for 3D visualization.
  dev_url: https://github.com/K3D-tools/K3D-jupyter

extra:
  recipe-maintainers:
    - tgandor
    - artur-trzesiok
    - marcinofulus
