{% set name = "k3d" %}
{% set version = "2.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7dd41fe72a51065d302f04761502f965378693f12bf3a831152b61ce00050c4c

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - jupyterlab ~=3.0
    - hatchling >=1.10.0
    - hatch-nodejs-version >=0.3.0
    - hatch-jupyter-builder >=0.6.2
  run:
    - python >={{ python_min }}
    - ipywidgets >=7.0.1
    - traittypes
    - traitlets
    - numpy >=1.11.0
    - msgpack-python
test:
  imports:
    - k3d
  requires:
    - pip
    - jupyterlab ~=3.0
    - python {{ python_min }}
  commands:
    - pip deepcomparer
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - cat labextensions | grep "k3d.*OK"  # [unix]

about:
  home: http://github.com/K3D-tools/K3D-jupyter
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Jupyter notebook extension for 3D visualization.
  dev_url: https://github.com/K3D-tools/K3D-jupyter

extra:
  recipe-maintainers:
    - tgandor
    - artur-trzesiok
    - marcinofulus
