{% set name = "k3d" %}
{% set version = "2.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c297e0e5a20d7b42c3cb78539173d62ee66451a8abf25913d33cdfba563dd681

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - setuptools
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ipywidgets >=7.0.1
    - jupyter-packaging
    - traittypes
    - traitlets
    - numpy >=1.11.0
test:
  commands:
    - cd {{ SRC_DIR }}/k3d && xvfb-run -a pytest  # [linux]
  requires:
    - pytest

about:
  home: http://github.com/K3D-tools/K3D-jupyter
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Jupyter notebook extension for 3D visualization.
  dev_url: https://github.com/K3D-tools/K3D-jupyter

extra:
  recipe-maintainers:
    - tgandor
    - artur-trzesiok
    - marcinofulus
