{% set name = "k3d" %}
{% set version = "2.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c93598fb896af498ee490c8e5bea1bab13507fcf8fd0bf11b2fc4249334ad451

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=40.8.0
    - jupyter-packaging ~=0.7.9
    - jupyterlab ~=3.0
  run:
    - python >=3.6
    - ipywidgets >=7.0.1
    - traittypes
    - traitlets
    - numpy >=1.11.0
    - msgpack-python
test:
  imports:
    - k3d
  requires:
    - pip
    - jupyterlab ~=3.0
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - cat labextensions | grep "k3d.*OK"  # [unix]

about:
  home: http://github.com/K3D-tools/K3D-jupyter
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Jupyter notebook extension for 3D visualization.
  dev_url: https://github.com/K3D-tools/K3D-jupyter

extra:
  recipe-maintainers:
    - tgandor
    - artur-trzesiok
    - marcinofulus
